stages:
  - i18n
  - github
  - linting
  - test
  - deploy
  - test_ui
  - cleanup
  - distribute

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  CI_KEYCHAIN_NAME: $CI_JOB_ID
  # We use this variable when we run publish-github jobs
  RELEASE_GITHUB_REPOSITORY: git@github.com:ProtonVPN/ios-mac-app.git
  GIT_SUBMODULE_FORCE_HTTPS: "true"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || 
          $CI_PIPELINE_SOURCE == "schedule" ||
          $CI_COMMIT_BRANCH == "develop"
      variables:
        # also deploy on MRs and schedules
        ATLAS_DEPLOY_ENV: "true"
    # run tests without env deployment
    - if: $CI_COMMIT_TAG

include:
  - project: 'proton/devops/atlas-deploy'
    ref: main
    file: '/scenarios/pipeline-env.yml'

  - project: 'translations/generator'
    ref: master
    file: '/jobs/sync-crowdin.gitlab-ci.yml'

  - project: 'translations/generator'
    ref: master
    file: '/jobs/commit-locales.gitlab-ci.yml'

  - project: 'agarroux/publish-github'
    ref: feat/github-app
    file: '/jobs/release.gitlab-ci.yml'
  
  # Include all jobs from all the files on `.gitlab/jobs/` folder
  - local: '.gitlab/jobs/*.yml'


linting:commit-quality:
  stage: linting
  image: protonjohn/commitlint-docker:latest
  interruptible: true
  script:
    - export NO_VIRTUALENV="YES"
    - scripts/git-cz setup
    - scripts/git-cz lintci
  rules:

# Runs a script that goes through all out apps and lib folders and lints them if .swiftlint file is available.
#
# More info on how it works:
# https://blog.kulman.sk/using-swiftlint-for-gitlab-code-quality/
linting:code-quality:
  extends:
    - .mr_job_template
    - .ios_job_template
  stage: linting
  artifacts:
    paths:
      - codequality_report.json
    reports:
      codequality: codequality_report.json
  script:    
    - scripts/code_quality.sh
  rules:

# Reenable when/if we have a license
#sonarqube-check:
#  stage: linting
#  image:
#    name: sonarsource/sonar-scanner-cli:latest
#    entrypoint: [""]
#  variables:
#    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
#    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
#  cache:
#    key: "${CI_JOB_NAME}"
#    paths:
#      - .sonar/cache
#  script:
#    - sonar-scanner
#  allow_failure: true
#  rules:
#    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
#      when: always
#    - if: $CI_COMMIT_BRANCH == "develop"
#      when: always
#    - when: manual
