// Objective-C API for talking to gitlab.protontech.ch/ProtonVPN/clients-shared/ed25519 Go package.
//   gobind -lang=objc gitlab.protontech.ch/ProtonVPN/clients-shared/ed25519
//
// File is generated by gobind. Do not edit.

#ifndef __Ed25519_H__
#define __Ed25519_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class Ed25519KeyPair;

@interface Ed25519KeyPair : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init;
- (NSData* _Nullable)privateKeyBytes;
/**
 * Private key in PKIX, ASN.1 DER format
 */
- (NSData* _Nullable)privateKeyPKIX;
/**
 * Private key PKIX, ASN.1 DER in Base64
 */
- (NSString* _Nonnull)privateKeyPKIXBase64;
/**
 * Private key ASN.1 DER representation as PEM
 */
- (NSString* _Nonnull)privateKeyPKIXPem;
- (NSData* _Nullable)publicKeyBytes;
/**
 * Public key in PKIX, ASN.1 DER format
 */
- (NSData* _Nullable)publicKeyPKIX:(NSError* _Nullable* _Nullable)error;
/**
 * Public key PKIX, ASN.1 DER in Base64
 */
- (NSString* _Nonnull)publicKeyPKIXBase64:(NSError* _Nullable* _Nullable)error;
/**
 * Public key ASN.1 DER representation as PEM
 */
- (NSString* _Nonnull)publicKeyPKIXPem:(NSError* _Nullable* _Nullable)error;
/**
 * Converts to X25519 secret key.
 */
- (NSData* _Nullable)toX25519;
/**
 * Converts to X25519 secret key encoded as base64.
 */
- (NSString* _Nonnull)toX25519Base64;
@end

/**
 * used only for testing
 */
FOUNDATION_EXPORT Ed25519KeyPair* _Nullable Ed25519CreateKeyPair(NSData* _Nullable pri, NSData* _Nullable pub);

FOUNDATION_EXPORT Ed25519KeyPair* _Nullable Ed25519NewKeyPair(NSError* _Nullable* _Nullable error);

#endif
