
// Objective-C API for talking to the following Go packages
//
//	github.com/ProtonMail/go-srp
//
// File is generated by gomobile bind. Do not edit.
#ifndef __SRP_FRAMEWORK_H__
#define __SRP_FRAMEWORK_H__

#include "Srp.objc.h"
#include "Universe.objc.h"

#endif
