# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

#update_fastlane

default_platform :mac

platform :mac do
  before_all do
    prepare_signing
  end

  after_all do
    delete_keychain(
      name: ENV["DEVELOPER_KEYCHAIN_NAME"]
    )
  end

  private_lane :prepare_signing do
    create_keychain(
      name: ENV["DEVELOPER_KEYCHAIN_NAME"],
      password: ENV["DEVELOPER_KEYCHAIN_PASSWORD"],
      default_keychain: false,
      add_to_search_list: true,
      unlock: true
    )
    import_certificate(
      keychain_name: ENV["DEVELOPER_KEYCHAIN_NAME"],
      keychain_password: ENV["DEVELOPER_KEYCHAIN_PASSWORD"],
      certificate_path: 'Certificates.p12',
      certificate_password: ENV["DEVELOPER_CERTIFICATE_PASSWORD"]
    )
  end

  desc "Run all the tests"
  lane :ci_test do
    clear_derived_data
    scan(
      scheme: "ProtonVPN",
      clean: true,
      result_bundle: true
    )
  end
end
