# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
 devices([
   "iPhone 8",
   "iPhone 8 Plus",
   "iPhone 12",
   "iPhone 12 Pro",
   "iPhone 12 Pro Max",
   "iPad Pro (9.7-inch)",
   "iPad Pro (12.9-inch) (4th generation)",
 ])

languages([
  "pl-PL",
  "it-IT",
  "es-ES",
  "es-MX",
  "fr-FR",
  "nl-NL",
  "pt-PT",
  "ru-RU",
  "fa-FA",
  "de-DE",
  "en-US",
])

scheme("ProtonVPN")
output_directory("./fastlane/screenshots")
clear_previous_screenshots(true)
clean(false)
xcargs("-UseModernBuildSystem=NO")
concurrent_simulators(true)
number_of_retries 0
skip_open_summary(true)

### Info for running screenshots manually (not from CI)
# If your screenshots and tests are too slow:
# Uncomment next lines and enter your devided data path, so app is not rebuilt for every device/language pair.
# Before running snapshot, run tests in xcode (with simulator), so the latest code is compiled
# and is present in derived data folder.

#test_without_building(true)
#derived_data_path("/Users/" + ENV["USER"] + "/Library/Developer/Xcode/DerivedData/ProtonVPN-forfugnubukkuofzikvrrodqzevg")
