// Objective-C API for talking to gitlab.protontech.ch/ProtonVPN/clients-shared/localAgent Go package.
//   gobind -lang=objc gitlab.protontech.ch/ProtonVPN/clients-shared/localAgent
//
// File is generated by gobind. Do not edit.

#ifndef __LocalAgent_H__
#define __LocalAgent_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class LocalAgentAgentConnection;
@class LocalAgentErrorMessage;
@class LocalAgentFeatures;
@class LocalAgentGetMessage;
@class LocalAgentReason;
@class LocalAgentStatusMessage;
@protocol LocalAgentNativeClient;
@class LocalAgentNativeClient;

@protocol LocalAgentNativeClient <NSObject>
- (void)log:(NSString* _Nullable)text;
- (void)onError:(long)code description:(NSString* _Nullable)description;
- (void)onState:(NSString* _Nullable)state;
@end

@interface LocalAgentAgentConnection : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(NSString* _Nullable)clientCertPEM clientKeyPEM:(NSString* _Nullable)clientKeyPEM serverCAsPEM:(NSString* _Nullable)serverCAsPEM host:(NSString* _Nullable)host client:(id<LocalAgentNativeClient> _Nullable)client features:(LocalAgentFeatures* _Nullable)features;
@property (nonatomic) NSString* _Nonnull state;
@property (nonatomic) LocalAgentStatusMessage* _Nullable status;
- (void)close;
- (void)setFeatures:(LocalAgentFeatures* _Nullable)features;
@end

@interface LocalAgentErrorMessage : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long code;
@property (nonatomic) NSString* _Nonnull description;
@end

@interface LocalAgentFeatures : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init;
- (BOOL)getBool:(NSString* _Nullable)name;
- (long)getInt:(NSString* _Nullable)name;
- (NSString* _Nonnull)getString:(NSString* _Nullable)name;
- (BOOL)hasFeature:(NSString* _Nullable)name;
// skipped method Features.Keys with unsupported parameter or return types

- (NSData* _Nullable)marshalJSON:(NSError* _Nullable* _Nullable)error;
- (void)setBool:(NSString* _Nullable)name value:(BOOL)value;
- (void)setInt:(NSString* _Nullable)name value:(long)value;
- (void)setString:(NSString* _Nullable)name value:(NSString* _Nullable)value;
- (BOOL)unmarshalJSON:(NSData* _Nullable)data error:(NSError* _Nullable* _Nullable)error;
@end

@interface LocalAgentGetMessage : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@end

@interface LocalAgentReason : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long code;
@property (nonatomic) BOOL final;
@property (nonatomic) NSString* _Nonnull description;
@end

@interface LocalAgentStatusMessage : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull state;
@property (nonatomic) LocalAgentFeatures* _Nullable features;
@property (nonatomic) LocalAgentReason* _Nullable reason;
@property (nonatomic) NSString* _Nonnull switchTo;
@end

FOUNDATION_EXPORT NSString* _Nonnull const LocalAgentStateConnected;
FOUNDATION_EXPORT NSString* _Nonnull const LocalAgentStateConnecting;
FOUNDATION_EXPORT NSString* _Nonnull const LocalAgentStateConnectionError;
FOUNDATION_EXPORT NSString* _Nonnull const LocalAgentStateDisconnected;
FOUNDATION_EXPORT NSString* _Nonnull const LocalAgentStateHardJailed;
FOUNDATION_EXPORT NSString* _Nonnull const LocalAgentStateServerCertificateError;
FOUNDATION_EXPORT NSString* _Nonnull const LocalAgentStateSoftJailed;

// skipped function CreateMessage with unsupported parameter or return types


FOUNDATION_EXPORT LocalAgentAgentConnection* _Nullable LocalAgentNewAgentConnection(NSString* _Nullable clientCertPEM, NSString* _Nullable clientKeyPEM, NSString* _Nullable serverCAsPEM, NSString* _Nullable host, id<LocalAgentNativeClient> _Nullable client, LocalAgentFeatures* _Nullable features, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT LocalAgentFeatures* _Nullable LocalAgentNewFeatures(void);

@class LocalAgentNativeClient;

@interface LocalAgentNativeClient : NSObject <goSeqRefInterface, LocalAgentNativeClient> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)log:(NSString* _Nullable)text;
- (void)onError:(long)code description:(NSString* _Nullable)description;
- (void)onState:(NSString* _Nullable)state;
@end

#endif
