//
//  LocalizedStrings.swift
//  vpncore - Created on 26.06.19.
//
//  Copyright (c) 2019 Proton Technologies AG
//
//  This file is part of vpncore.
//
//  vpncore is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  vpncore is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with vpncore.  If not, see <https://www.gnu.org/licenses/>.

import Foundation

public class LocalizedString {
    
    // MARK: - General
    public static let cancel = NSLocalizedString("_cancel")
    public static let connect = NSLocalizedString("_connect")
    public static let connected = NSLocalizedString("_connected")
    public static let delete = NSLocalizedString("_delete")
    public static let disconnect = NSLocalizedString("_disconnect")
    public static let disconnected = NSLocalizedString("_disconnected")
    public static let done = NSLocalizedString("_done")
    public static let edit = NSLocalizedString("_edit")
    public static let ok = NSLocalizedString("_ok")
    public static let save = NSLocalizedString("_save")
    public static let unavailable = NSLocalizedString("_unavailable")
    public static let warning = NSLocalizedString("_warning")
    public static let upgrade = NSLocalizedString("_upgrade")
    public static let upgradeSubscription = NSLocalizedString("_upgrade_subscription")
    public static let upgradeRequired = NSLocalizedString("_upgrade_required")
    public static let maintenance = NSLocalizedString("_maintenance")
    public static let quit = NSLocalizedString("_quit")
    public static let quitWarning = NSLocalizedString("_quit_warning")
    public static let enabled = NSLocalizedString("_enabled")
    public static let disabled = NSLocalizedString("_disabled")
    public static let disable = NSLocalizedString("_disable")
    public static let report = NSLocalizedString("_report")
    public static let ignore = NSLocalizedString("_ignore")
    public static let info = NSLocalizedString("_info")
    public static let `continue` = NSLocalizedString("_continue")
    public static let here = NSLocalizedString("_here")
    public static let networkUnreachable = NSLocalizedString("_network_unreachable")
    public static let notConnectedToTheInternet = NSLocalizedString("_not_connected_to_the_internet")
    public static let vpnConnectionActive = NSLocalizedString("_vpn_connection_active")
    public static let logOut = NSLocalizedString("_log_out")
    public static let logOutWarning = NSLocalizedString("_log_out_warning")
    public static let logOutWarningLong = NSLocalizedString("_log_out_warning_long")
    public static let loadingScreenSlogan = NSLocalizedString("_loading_screen_slogan")
    public static let reportAnIssue = NSLocalizedString("_report_an_issue")
    public static let help = NSLocalizedString("_help")
    public static let learnMore = NSLocalizedString("_learn_more")
    public static let ip = NSLocalizedString("_ip")
    public static let ipValue = NSLocalizedString("_ip_value")
    public static let publicIp = NSLocalizedString("_public_ip")
    public static let quickConnect = NSLocalizedString("_quick_connect")
    public static let connectTo = NSLocalizedString("_connect_to")
    public static let secureCore = NSLocalizedString("_secure_core")
    public static let secureCoreCountry = NSLocalizedString("_secure_core_country")
    public static let country = NSLocalizedString("_country")
    public static let showProtonVpn = NSLocalizedString("_show_protonvpn")
    public static let clearApplicationData = NSLocalizedString("_clear_application_data")
    public static let preparingConnection = NSLocalizedString("_preparing_connection")
    public static let connectingTo = NSLocalizedString("_connecting_to")
    public static let connectedTo = NSLocalizedString("_connected_to")
    public static let connecting = NSLocalizedString("_connecting")
    public static let connectingDotDotDot = NSLocalizedString("_connecting...")
    public static let connectingVpn = NSLocalizedString("_connecting_vpn")
    public static let vpnConnected = NSLocalizedString("_connected_to_vpn")
    public static let notConnected = NSLocalizedString("_not_connected")
    public static let youAreNotConnected = NSLocalizedString("_you_are_not_connected")
    public static let tryAgain = NSLocalizedString("_try_agian")
    public static let retry = NSLocalizedString("_retry")
    public static let freeServers = NSLocalizedString("_free_servers")
    public static let basicServers = NSLocalizedString("_basic_servers")
    public static let plusServers = NSLocalizedString("_plus_servers")
    public static let initializingConnection = NSLocalizedString("_initializing_connection")
    public static let successfullyConnected = NSLocalizedString("_successfully_connected")
    public static let failed = NSLocalizedString("_failed")
    public static let connectionFailed = NSLocalizedString("_connection_failed")
    public static let timedOut = NSLocalizedString("_timed_out")
    public static let status = NSLocalizedString("_status")
    public static let sessionTime = NSLocalizedString("_session_time")
    public static let location = NSLocalizedString("_location")
    public static let city = NSLocalizedString("_city")
    public static let technicalDetails = NSLocalizedString("_technical_details")
    public static let openAppToLogIn = NSLocalizedString("_open_app_to_log_in")
    public static let upgradeToPlus = NSLocalizedString("_upgrade_to_plus")
    public static let upgradeForSecureCore = NSLocalizedString("_upgrade_for_secure_core")
    public static let on = NSLocalizedString("_switch_side_button_on", comment: "Custom switch on")
    public static let off = NSLocalizedString("_switch_side_button_off", comment: "Custom switch off")
    
    public static let countriesCount = NSLocalizedString("_countries_count")
    public static let countriesFree = NSLocalizedString("_countries_free")
    public static let countriesPremium = NSLocalizedString("_countries_premium")
    public static let close = NSLocalizedString("_close")
    
    // MARK: - Notifications
    public static let killSwitchBlockingConnection = NSLocalizedString("_kill_switch_blocking_connection")
    public static let alwaysOnWillReconnect = NSLocalizedString("_always_on_will_reconnect")
    
    // MARK: - About
    public static let about = NSLocalizedString("_about")
    public static let version = NSLocalizedString("_version")
    public static let versionCurrent = NSLocalizedString("_version_current")
    public static let releaseDate = NSLocalizedString("_release_date")
    public static let changelog = NSLocalizedString("_changelog")
    public static let acknowledgements = NSLocalizedString("_acknowledgements")
    
    // MARK: - Login & Signup
    public static let username = NSLocalizedString("_username")
    public static let password = NSLocalizedString("_password")
    public static let passwordConfirm = NSLocalizedString("_password_confirm")
    public static let show = NSLocalizedString("_show")
    public static let hide = NSLocalizedString("_hide")
    public static let login = NSLocalizedString("_login")
    public static let logIn = NSLocalizedString("_log_in")
    public static let rememberLogin = NSLocalizedString("_remember_login")
    public static let startOnBoot = NSLocalizedString("_start_on_boot")
    public static let createAccount = NSLocalizedString("_create_account")
    public static let needHelp = NSLocalizedString("_need_help")
    public static let resetPassword = NSLocalizedString("_reset_password")
    public static let forgotUsername = NSLocalizedString("_forgot_username")
    public static let forgotPassword = NSLocalizedString("_forgot_password")
    public static let signUp = NSLocalizedString("_sign_up")
    public static let warningVpnSessionIsActive = NSLocalizedString("_warning_vpn_session_is_active")
    public static let enterEmailAddress = NSLocalizedString("_enter_email_address")
    public static let phoneCountryCodePlaceholder = NSLocalizedString("_phone_country_code_placeholder")
    public static let phoneNumberPlaceholder = NSLocalizedString("_phone_number_placeholder")
    public static let selectPhoneCountryCode = NSLocalizedString("_select_phone_country_code")
    public static let searchPhoneCountryCodePlaceholder = NSLocalizedString("_search_phone_country_code_placeholder")
    public static let alreadyHaveAccount = NSLocalizedString("_already_have_account")
    public static let getVerificationEmail = NSLocalizedString("_get_verification_email")
    public static let getVerificationSms = NSLocalizedString("_get_verification_sms")
    public static let selectVerificationOption = NSLocalizedString("_select_verification_option")
    public static let selectVerificationOptionTopMessage = NSLocalizedString("_select_verification_option_top_message")
    public static let useCaptchaVerification = NSLocalizedString("_use_captcha_verification")
    public static let useOtherEmailAddress = NSLocalizedString("_use_other_email_address")
    public static let useSMSVerification = NSLocalizedString("_use_sms_verification")
    public static let requestInvitation = NSLocalizedString("_request_invitation")
    public static let enterVerificationCode = NSLocalizedString("_enter_verification_code")
    public static let submitVerificationCode = NSLocalizedString("_submit_verification_code")
    public static let resendCode = NSLocalizedString("_resend_code")
    public static let resendNoCode = NSLocalizedString("_resend_no_code")
    public static let resendSuccess = NSLocalizedString("_resend_success")
    public static let termsAndConditions = NSLocalizedString("_terms_and_conditions")
    public static let termsAndConditionsDisclaimer = NSLocalizedString("_terms_and_conditions_disclaimer")
    public static let privacyPolicy = NSLocalizedString("_privacy_policy")
    public static let verificationInstructions = NSLocalizedString("_verification_instructions")
    public static let setupComplete = NSLocalizedString("_setup_complete")
    public static let setupCompleteFree = NSLocalizedString("_setup_complete_free")
    public static let setupCompleteBasic = NSLocalizedString("_setup_complete_basic")
    public static let setupCompletePlus = NSLocalizedString("_setup_complete_plus")
    public static let dataDisclaimerTitle = NSLocalizedString("_data_disclaimer_title")
    public static let dataDisclaimerText = NSLocalizedString("_data_disclaimer_text")
    public static let dataDisclaimerUserDetails = NSLocalizedString("_data_disclaimer_user_details")
    public static let dataDisclaimerDeviceDetails = NSLocalizedString("_data_disclaimer_device_details")
    public static let dataDisclaimerAgree = NSLocalizedString("_data_disclaimer_agree")
    
    // MARK: - Map
    public static let map = NSLocalizedString("_map")
    public static let mapShow = NSLocalizedString("_map_show")
    public static let mapHide = NSLocalizedString("_map_hide")
    
    // MARK: - Servers
    public static let torDescription = NSLocalizedString("_tor_description")
    public static let p2pDescription = NSLocalizedString("_p2p_description")
    public static let premiumDescription = NSLocalizedString("_premium_description")
    public static let viaCountry = NSLocalizedString("_via_country")
    public static let via = NSLocalizedString("_via")
    public static let youAreNotProtected = NSLocalizedString("_you_are_not_protected")
    public static let load = NSLocalizedString("_load")
    public static let countries = NSLocalizedString("_countries")
    public static let noServersToShow = NSLocalizedString("_no_servers_to_show")
    public static let planDoesNotIncludeSecureCore = NSLocalizedString("_plan_does_not_include_secure_core")
    public static let learnMoreAboutSecureCore = NSLocalizedString("_learn_more_about_secure_core")
    public static let searchForCountry = NSLocalizedString("_search_for_country")
    public static let secureCoreInfo = NSLocalizedString("_secure_core_info")
    public static let viewToggleWillCauseDisconnect = NSLocalizedString("_view_toggle_will_cause_disconnect")
    public static let serverLoad = NSLocalizedString("_server_load")
    public static let serverIp = NSLocalizedString("_server_ip")
    public static let autoAssigned = NSLocalizedString("_auto_assigned")
    public static let premiumServer = NSLocalizedString("_premium_server")
    public static let standard = NSLocalizedString("_standard")
    public static let p2p = NSLocalizedString("_p2p")
    public static let tor = NSLocalizedString("_tor")
    public static let p2pServer = NSLocalizedString("_p2p_server")
    public static let torServer = NSLocalizedString("_tor_server")
    
    // MARK: - Profiles
    public static let profile = NSLocalizedString("_profile")
    public static let profiles = NSLocalizedString("_profiles")
    public static let recommended = NSLocalizedString("_recommended")
    public static let myProfiles = NSLocalizedString("_my_profiles")
    public static let saveAsProfile = NSLocalizedString("_save_as_profile")
    public static let deleteProfile = NSLocalizedString("_delete_profile")
    public static let profileDeletedSuccessfully = NSLocalizedString("_profile_deleted_successfully")
    public static let profileDeletionFailed = NSLocalizedString("_profile_deletion_failed")
    public static let createNewProfile = NSLocalizedString("_create_new_profile")
    public static let manageProfiles = NSLocalizedString("_manage_profiles")
    public static let profilesOverview = NSLocalizedString("_profiles_overview")
    public static let profileCreatedSuccessfully = NSLocalizedString("_profile_created_successfully")
    public static let profileCreationFailed = NSLocalizedString("_profile_creation_failed")
    public static let profileEditedSuccessfully = NSLocalizedString("_profile_edited_successfully")
    public static let overview = NSLocalizedString("_overview")
    public static let connection = NSLocalizedString("_connection")
    public static let action = NSLocalizedString("_action")
    public static let `default` = NSLocalizedString("_default")
    public static let fastest = NSLocalizedString("_fastest")
    public static let fastestAvailableServer = NSLocalizedString("_fastest_available_server")
    public static let fastestConnection = NSLocalizedString("_fastest_connection")
    public static let random = NSLocalizedString("_random")
    public static let randomAvailableServer = NSLocalizedString("_random_available_server")
    public static let randomConnection = NSLocalizedString("_random_connection")
    public static let differentServerEachTime = NSLocalizedString("_different_server_each_time")
    public static let noDescriptionAvailable = NSLocalizedString("_no_description_available")
    public static let createNewProfileHeader = NSLocalizedString("_create_profile")
    public static let profileSettings = NSLocalizedString("_profile_settings")
    public static let connectionSettings = NSLocalizedString("_connection_settings")
    public static let name = NSLocalizedString("_name")
    public static let enterProfileName = NSLocalizedString("_enter_profile_name")
    public static let color = NSLocalizedString("_color")
    public static let makeDefaultProfile = NSLocalizedString("_make_default_profile")
    public static let defaultProfileTooltip = NSLocalizedString("_default_profile_tooltip")
    public static let serverType = NSLocalizedString("_feature")
    public static let useSecureCore = NSLocalizedString("_use_secure_core")
    public static let selectCountry = NSLocalizedString("_select_country")
    public static let server = NSLocalizedString("_server")
    public static let selectServer = NSLocalizedString("_select_server")
    public static let profileNameIsRequired = NSLocalizedString("_profile_name_is_required")
    public static let profileNameIsTooLong = NSLocalizedString("_profile_name_is_too_long")
    public static let countrySelectionIsRequired = NSLocalizedString("_country_selection_is_required")
    public static let serverSelectionIsRequired = NSLocalizedString("_server_selection_is_required")
    public static let profileNameUnique = NSLocalizedString("_profile_name_needs_to_be_unique")
    public static let serverCombinationUnique = NSLocalizedString("_country_and_server_combination_needs_to_be_unique")
    public static let currentSelectionWillBeLost = NSLocalizedString("_current_selection_will_be_lost")
    public static let checkIfFieldsPresent = NSLocalizedString("_check_if_fields_present")
    public static let deleteProfileHeader = NSLocalizedString("_delete_profile")
    public static let deleteProfileWarning = NSLocalizedString("_delete_profile_warning")
    public static let selectProfileColor = NSLocalizedString("_select_profile_color")
    
    public static let planSpeedMedium = NSLocalizedString("_plan_speed_medium")
    public static let planSpeedHigh = NSLocalizedString("_plan_speed_high")
    public static let planSpeedFastests = NSLocalizedString("_plan_speed_fastest")
    
    // MARK: - Errors
    public static let errorInternalError = NSLocalizedString("_error_internal_error")
    public static let errorVpnSessionIsActive = NSLocalizedString("_error_vpn_session_is_active")
    public static let errorUserHasNoVpnAccess = NSLocalizedString("_error_user_has_no_vpn_access")
    public static let errorUserHasNotSignedUp = NSLocalizedString("_error_user_has_not_signed_up")
    public static let errorUserIsOnWaitlist = NSLocalizedString("_error_user_is_on_waitlist")
    public static let errorUserCredentialsMissing = NSLocalizedString("_error_user_credentials_missing")
    public static let errorUserCredentialsExpired = NSLocalizedString("_error_user_credentials_expired")
    public static let errorVpnCredentialsMissing = NSLocalizedString("_error_vpn_credentials_missing")
    public static let errorDecode = NSLocalizedString("_error_decode")
    public static let errorEmailVerificationDisabled = NSLocalizedString("_error_email_verification_disabled")
    
    public static let errorFieldRequired = NSLocalizedString("_error_field_required")
    public static let errorFielWrongdEmailFormat = NSLocalizedString("_error_field_email_wrong_format")
    public static let errorFieldPasswordDontMatch = NSLocalizedString("_error_field_passwords_dont_match")
    public static let errorFieldUnknown = NSLocalizedString("_error_field_unknown")
    
    public static let errorUserCancelled = NSLocalizedString("_error_user_cancelled")
    public static let errorUserFailedHumanValidation = NSLocalizedString("_error_user_failed_human_validation")
    
    public static let errorApplyPaymentOnRegistrationTitle = NSLocalizedString("_error_apply_payment_failed_on_registration_title")
    public static let errorApplyPaymentOnRegistrationMessage = NSLocalizedString("_error_apply_payment_failed_on_registration_message")
    public static let errorApplyPaymentOnRegistrationSupport = NSLocalizedString("_error_apply_payment_failed_on_registration_support")
    
    // MARK: - Password encoding errors
    public static let errorModulusSignature = NSLocalizedString("_error_modulus_signature", comment: "error when try to parse modulus signature")
    public static let errorGenerateSrp = NSLocalizedString("_error_generate_srp", comment: "error when generate srp clint")
    public static let errorHashPassword = NSLocalizedString("_error_hash_password", comment: "error when try to hash password")
    public static let errorFetchSession = NSLocalizedString("_error_fetch_session", comment: "error try to restore user from the session")
    
    // MARK: - Network errors
    public static let neRequestTimedOut = NSLocalizedString("_ne_request_timed_out")
    public static let neUnableToConnectToHost = NSLocalizedString("_ne_unable_to_connect_to_host")
    public static let neNetworkConnectionLost = NSLocalizedString("_ne_network_connection_lost")
    public static let neNotConnectedToTheInternet = NSLocalizedString("_ne_not_connected_to_the_internet")
    
    // MARK: - API errors
    public static let aeWrongLoginCredentials = NSLocalizedString("_ae_wrong_login_credentials")
    public static let aeVpnInfoNotReceived = NSLocalizedString("_ae_vpn_info_not_received")
    public static let errorServerInfoParser = NSLocalizedString("_error_server_info_parser", comment: "error when try to parse the server info")
    public static let errorVpnProperties = NSLocalizedString("_error_vpn_properties", comment: "default error when vpn properties fetch failed")
    public static let errorSessionCountParser = NSLocalizedString("_error_session_count_parser")
    public static let errorExistingSessionToServer = NSLocalizedString("_error_existing_session_to_server")
    public static let errorLoads = NSLocalizedString("_error_loads")
    public static let errorApiOffline = NSLocalizedString("_error_api_offline")
    public static let errorSubscriptionParser = NSLocalizedString("_error_subscription_parser", comment: "error when try to parse subscription info")
    public static let errorVerificationMethodsParser = NSLocalizedString("_error_verification_methods_parser", comment: "error when try to parse verification methods")
    public static let errorUsernameUnavailable = NSLocalizedString("_error_username_unavailable", comment: "username unavailable error")
    public static let errorKeychainFetch = NSLocalizedString("_error_keychain_fetch")
    public static let errorUserCreation = NSLocalizedString("_error_user_creation", comment: "error when the app fails to create a user")
    public static let errorSignupUsingProtonMailAddress = NSLocalizedString("_error_signup_using_protonmail_address", comment: "error when the user attempts to sign up using an existing ProtonMail email address")
    
    public static let errorUnknownTitle = NSLocalizedString("_error_unknown_title")
    
    public static let errorMITMTitle = NSLocalizedString("_error_mitm_title")
    public static let errorMITMdescription = NSLocalizedString("_error_mitm_description")
    
    public static let errorInvalidHumanVerificationCodeTitle = NSLocalizedString("_error_invalid_human_verification_code_title")
    public static let errorInvalidHumanVerificationCodeMessage = NSLocalizedString("_error_invalid_human_verification_code_message")
    public static let errorInvalidHumanVerificationCodeTryOther = NSLocalizedString("_error_invalid_human_verification_code_try_other")
    public static let errorInvalidHumanVerificationCodeResend = NSLocalizedString("_error_invalid_human_verification_code_resend")
    
    // MARK: - IAP errors
    public static let errorOccured = NSLocalizedString("_error_occured")
    public static let errorUnavailableProduct = NSLocalizedString("_error_unavailable_product")
    public static let errorReceiptLost = NSLocalizedString("_error_receipt_lost")
    public static let errorTransactionOfOtherUser = NSLocalizedString("_error_transaction_of_other_user")
    public static let errorPurchasedPlanDoesNotMatchAvailable = NSLocalizedString("_error_purchased_plan_does_not_match_available")
    public static let errorSandboxReceipt = NSLocalizedString("_error_sandbox_receipt")
    public static let errorCreditsApplied = NSLocalizedString("_error_credit_applied")
    public static let errorTransactionFailedByUnknownReason = NSLocalizedString("_error_transaction_failed_by_unknown_reason")
    public static let errorNoActiveUsername = NSLocalizedString("_error_no_active_username")
    public static let errorNoNewSubscriptionInSuccessfullResponse = NSLocalizedString("_error_no_new_subscription_in_successfull_response")
    
    // MARK: - Alerts
    public static let delinquentUserTitle = NSLocalizedString("_delinquent_user_title")
    public static let delinquentUserDescription = NSLocalizedString("_delinquent_user_description")
    public static let existingSession = NSLocalizedString("_existing_session")
    public static let existingSessionToServer = NSLocalizedString("_existing_session_to_server")
    public static let failedToAccessVpnCredentialsTitle = NSLocalizedString("_failed_to_access_vpn_credentials_title")
    public static let failedToAccessVpnCredentialsDescription = NSLocalizedString("_failed_to_access_vpn_credentials_description")
    public static let p2pForwardedPopUpTitle = NSLocalizedString("_p2p_forwarded_popup_title")
    public static let p2pDetectedPopUpTitle = NSLocalizedString("_p2p_detected_popup_title")
    public static let p2pDetectedPopUpBody = NSLocalizedString("_p2p_detected_popup_body")
    public static let serverUnderMaintenance = NSLocalizedString("_server_under_maintenance")
    public static let sessionCountReachedTitle = NSLocalizedString("_session_count_reached_title")
    public static let sessionCountReachedDescription = NSLocalizedString("_session_count_reached_description")
    public static let upgradePlanToAccessCountry = NSLocalizedString("_upgrade_plan_to_access_country")
    public static let upgradePlanToAccessServer = NSLocalizedString("_upgrade_plan_to_access_server")
    public static let upgradePlanToAccessSecureCore1 = NSLocalizedString("_upgrade_plan_to_access_secure_core_p1")
    public static let upgradePlanToAccessSecureCore2 = NSLocalizedString("_upgrade_plan_to_access_secure_core_p2")
    
    public static let serversUnderMaintenance = NSLocalizedString("_servers_under_maintenance")
    public static let allServersInCountryUnderMaintenance = NSLocalizedString("_all_servers_in_country_under_maintenance")
    public static let countryServersUnderMaintenance = NSLocalizedString("_country_servers_under_maintenance")
    public static let allServersUnderMaintenance = NSLocalizedString("_all_servers_under_maintenance")
    public static let allServersInProfileUnderMaintenance = NSLocalizedString("_all_servers_in_profile_under_maintenance")
    
    public static let trialPopUpTitle = NSLocalizedString("_trial_popup_title")
    public static let trialPopUpIntroduction = NSLocalizedString("_trial_popup_introduction")
    public static let trialPopUpFreeUpgrade = NSLocalizedString("_trial_popup_free_upgrade")
    public static let trialPopUpCallToUpgrade = NSLocalizedString("_trial_popup_call_to_upgrade")
    public static let trialPopUpThanks = NSLocalizedString("_trial_popup_thanks")
    public static let trialPopUpExplanation = NSLocalizedString("_trial_popup_explanation")
    public static let trialPopUpFullSubscription = NSLocalizedString("_trial_popup_full_subscription")
    public static let trialPopUpEnjoy = NSLocalizedString("_trial_popup_enjoy")
        
    public static let trialWelcomeHeadingIos = NSLocalizedString("_trial_welcome_heading_iOS")
    public static let trialWelcomeDescriptionIos = NSLocalizedString("_trial_welcome_description_iOS")
    public static let trialWelcomeEndsInIos = NSLocalizedString("_trial_welcome_ends_in_iOS")
    public static let trialExpiredAlertTitleIos = NSLocalizedString("_trial_expired_alert_title_iOS")
    public static let trialExpiredAlertBodyIos = NSLocalizedString("_trial_expired_alert_body_iOS")
    
    public static let p2pForwardedPopUpBody = NSLocalizedString("_p2p_forwarded_popup_body")
    public static let p2pForwardedPopUpBodyP1 = NSLocalizedString("_p2p_forwarded_popup_body_p1")
    public static let p2pForwardedPopUpBodyP2 = NSLocalizedString("_p2p_forwarded_popup_body_p2")
    
    public static let vpnStuckDisconnectingTitle = NSLocalizedString("_vpn_stuck_disconnecting_title")
    public static let vpnStuckDisconnectingBody = NSLocalizedString("_vpn_stuck_disconnecting_body")
    
    public static let updateRequiredTitle = NSLocalizedString("_update_required")
    public static let updateRequiredDescription = NSLocalizedString("_update_required_no_longer_supported")
    public static let updateRequiredSupport = NSLocalizedString("_update_required_support")
    public static let updateUpdate = NSLocalizedString("_update_required_update")
    
    public static let invalidRefreshTokenTitle = NSLocalizedString("_invalid_refresh_token")
    public static let invalidRefreshTokenDescription = NSLocalizedString("_invalid_refresh_token_please_login")
    
    public static let protonVpnMacOS = NSLocalizedString("_protonvpn_macos")
    public static let neagentDescription = NSLocalizedString("_neagent_description")
    public static let neagentPassword = NSLocalizedString("_neagent_password")
    public static let macPassword = NSLocalizedString("_mac_password")
    public static let neagentFirstStep = NSLocalizedString("_neagent_first_step")
    public static let neagentAlwaysAllow = NSLocalizedString("_neagent_always_allow")
    public static let neagentSecondStep = NSLocalizedString("_neagent_second_step")
    public static let gotIt = NSLocalizedString("_got_it")
    
    public static let paidRequired = NSLocalizedString("_paid_required")
    public static let plusRequired = NSLocalizedString("_plus_required")
    
    public static let upgradeUnavailableTitle = NSLocalizedString("_upgrade_unavailable_title")
    public static let upgradeUnavailableBody = NSLocalizedString("_upgrade_unavailable_body")
    
    public static let deleteApplicationDataPopupTitle = NSLocalizedString("_delete_application_data_popup_title")
    public static let deleteApplicationDataPopupBody = NSLocalizedString("_delete_application_data_popup_body")
    
    public static let killSwitchBlockingTitle = NSLocalizedString("_kill_switch_blocking_title")
    public static let killSwitchBlockingBody = NSLocalizedString("_kill_switch_blocking_body")
    
    public static let killSwitchErrorTitle = NSLocalizedString("_kill_switch_error_title")
    public static let killSwitchErrorBody = NSLocalizedString("_kill_switch_error_body")
    
    public static let killSwitchHelperInstallPopupBody = NSLocalizedString("_kill_switch_helper_install_popup_body")
    public static let killSwitchHelperUpdatePopupBody = NSLocalizedString("_kill_switch_helper_update_popup_body")
    public static let killSwitchHelperInstallIssuePopupBody = NSLocalizedString("_kill_switch_helper_install_issue_popup_body")
    
    public static let existingFirewallPopupTitle = NSLocalizedString("_existing_firewall_popup_title")
    public static let existingFirewallPopupBody = NSLocalizedString("_existing_firewall_popup_body")
    
    // MARK: - Settings
    public static let preferences = NSLocalizedString("_preferences")
    public static let settings = NSLocalizedString("_settings")
    public static let account = NSLocalizedString("_account")
    public static let general = NSLocalizedString("_general")
    public static let accountType = NSLocalizedString("_account_type")
    public static let accountPlan = NSLocalizedString("_account_plan")
    public static let manageSubscription = NSLocalizedString("_manage_subscription_on_web")
    public static let killSwitch = NSLocalizedString("_kill_switch")
    public static let killSwitchTooltip = NSLocalizedString("_kill_switch_tooltip")
    public static let alwaysOnVpn = NSLocalizedString("_always_on_vpn")
    public static let alwaysOnVpnTooltipIos = NSLocalizedString("_always_on_vpn_tooltip_ios")
    public static let alwaysOnVpnConnectionWillRestart = NSLocalizedString("_always_on_vpn_connection_will_restart")
    public static let alwaysOnVpnConnectionWillDrop = NSLocalizedString("_always_on_vpn_connection_will_drop")
    public static let autoConnect = NSLocalizedString("_auto_connect")
    public static let autoConnectTooltip = NSLocalizedString("_auto_connect_tooltip")
    public static let quickConnectTooltip = NSLocalizedString("_quick_connect_tooltip")
    public static let startMinimized = NSLocalizedString("_start_minimized")
    public static let systemNotifications = NSLocalizedString("_system_notifications")
    public static let earlyAccess = NSLocalizedString("_early_access")
    public static let earlyAccessTooltip = NSLocalizedString("_early_access_tooltip")
    public static let dnsLeakProtection = NSLocalizedString("_dns_leak_protection")
    public static let dnsLeakProtectionTooltip = NSLocalizedString("_dns_leak_protection_tooltip")
    public static let securityOptions = NSLocalizedString("_security_options")
    public static let subscriptionPlan = NSLocalizedString("_subscription_plan")
    public static let choosePlan = NSLocalizedString("_choose_plan")
    public static let viewLogs = NSLocalizedString("_view_logs")
    public static let logs = NSLocalizedString("_logs")
    public static let activateWidget = NSLocalizedString("_activate_widget")
    public static let activateWidgetStep1 = NSLocalizedString("_activate_widget_step_1")
    public static let activateWidgetStep2 = NSLocalizedString("_activate_widget_step_2")
    public static let activateWidgetStep3 = NSLocalizedString("_activate_widget_step_3")
    public static let reportBug = NSLocalizedString("_report_bug")
    
    // MARK: - Plans
    public static let getPlan = NSLocalizedString("_get_plan")
    public static let freeCountries = NSLocalizedString("_free_countries")
    public static let allCountries = NSLocalizedString("_all_countries")
    public static let planConnection = NSLocalizedString("_plans_connection")
    public static let planConnections = NSLocalizedString("_plans_connections")
    public static let speed = NSLocalizedString("_speed")
    public static let medium = NSLocalizedString("_medium")
    public static let high = NSLocalizedString("_high")
    public static let highest = NSLocalizedString("_highest")
    public static let plusPlanFeatures = NSLocalizedString("_plus_plan_features")
    public static let free = NSLocalizedString("_free")
    public static let forAYear = NSLocalizedString("_for_a_year")
    public static let planUnavailableButton = NSLocalizedString("_plan_unavailable_button")
    public static let doYouWantToActivateSubscriptionFor = NSLocalizedString("_do_you_want_to_activate_subscription_for")
    public static let mostPopular = NSLocalizedString("_most_popular")
    public static let advancedFeatures = NSLocalizedString("_advanced_features")
    public static let selectPlan = NSLocalizedString("_select_plan")
    public static let plansFooter = NSLocalizedString("_plans_footer")
    public static let perYearShort = NSLocalizedString("_per_year_short")
    
    public static let featureServerCount = NSLocalizedString("_feature_server_count")
    public static let featureSpeed = NSLocalizedString("_feature_speed")
    public static let featureConnections = NSLocalizedString("_feature_connections")
    public static let featureSecureStreaming = NSLocalizedString("_feature_secure_streaming")
    public static let featureTor = NSLocalizedString("_feature_tor")
    public static let featureSecureCore = NSLocalizedString("_feature_secure_core")
    
    // MARK: - Upsell & Onboard - macOS
    public static let welcomeTitle = NSLocalizedString("_welcome_title")
    public static let welcomeDescription = NSLocalizedString("_welcome_description")
    public static let noThanks = NSLocalizedString("_no_thanks")
    public static let skip = NSLocalizedString("_skip")
    public static let takeTour = NSLocalizedString("_take_tour")
    
    public static let plus = NSLocalizedString("_plus")
    public static let enjoyForFree = NSLocalizedString("_enjoy_for_free")
    public static let protonVpnPlus = NSLocalizedString("_protonvpn_plus")
    public static let welcomeGiftDescription = NSLocalizedString("_welcome_gift_description")
    public static let p2pServers = NSLocalizedString("_p2p_servers")
    public static let connectionsAvailable = NSLocalizedString("_5_connections")
    public static let multipleCountries = NSLocalizedString("_multiple_countries")
    public static let expired = NSLocalizedString("_expired")
    
    public static let freeTrialExpiredTitle = NSLocalizedString("_free_trial_expired_title")
    public static let freeTrialExpiredDescription = NSLocalizedString("_free_trial_expired_description")
    public static let maybeLater = NSLocalizedString("_maybe_later")
    public static let upgradeNow = NSLocalizedString("_upgrade_now")
    public static let moneyBackGuarantee = NSLocalizedString("_money_back_guarantee")
    
    public static let plusUpgradeTitle = NSLocalizedString("_plus_upgrade_title")
    public static let plusUpgradeDescription = NSLocalizedString("_plus_upgrade_description")
    public static let upgradeMyPlan = NSLocalizedString("_upgrade_my_plan")
    
    public static let freeTrialAboutToExpireTitle = NSLocalizedString("_free_trial_about_to_expire_title")
    public static let freeTrialAboutToExpireDescription = NSLocalizedString("_free_trial_about_to_expire_description")
    public static let connectionsAvailableDescription = NSLocalizedString("_5_connections_description")
    public static let secureCoreDescription = NSLocalizedString("_secure_core_description")
    public static let multipleServersTitle = NSLocalizedString("_multiple_servers_title")
    public static let multipleServersDescription = NSLocalizedString("_multiple_servers_description")
    public static let secureStreamingTitle = NSLocalizedString("_secure_streaming_title")
    public static let secureStreamingDescription = NSLocalizedString("_secure_streaming_description")
    
    public static let quickConnectTourTitle = NSLocalizedString("_quick_connect_tour_title")
    public static let quickConnectTourDescription = NSLocalizedString("_quick_connect_tour_description")
    public static let profilesTourTitle = NSLocalizedString("_profiles_tour_title")
    public static let profilesTourDescription = NSLocalizedString("_profiles_tour_description")
    public static let countriesTourTitle = NSLocalizedString("_countries_tour_title")
    public static let countriesTourDescription = NSLocalizedString("_countries_tour_description")
    public static let secureCoreTourTitle = NSLocalizedString("_secure_core_tour_title")
    public static let secureCoreTourDescription = NSLocalizedString("_secure_core_tour_description")
    public static let mapTourTitle = NSLocalizedString("_map_tour_title")
    public static let mapTourDescription = NSLocalizedString("_map_tour_description")
    public static let nextTip = NSLocalizedString("_next_tip")
    public static let endTour = NSLocalizedString("_end_tour")
    
    // MARK: - Upsell & Onboard - iOS
    public static let iosOnboardingPage1Title = NSLocalizedString("_ios_onboarding_page1_title")
    public static let iosOnboardingPage1Description = NSLocalizedString("_ios_onboarding_page1_description")
    public static let iosOnboardingPage2Title = NSLocalizedString("_ios_onboarding_page2_title")
    public static let iosOnboardingPage2Description = NSLocalizedString("_ios_onboarding_page2_description")
    public static let iosOnboardingPage3Title = NSLocalizedString("_ios_onboarding_page3_title")
    public static let iosOnboardingPage3Description = NSLocalizedString("_ios_onboarding_page3_description")
    public static let next = NSLocalizedString("_next")
    public static let discoverTheApp = NSLocalizedString("_discover_the_app")
    
    // MARK: - Extensions
    public static let extensions = NSLocalizedString("_extensions")
    public static let widget = NSLocalizedString("_widget")
    public static let logInToUseWidget = NSLocalizedString("_log_in_to_use_widget")
    
    // MARK: - Report bugs
    public static let reportAttachments = NSLocalizedString("_report_attachments")
    public static let reportLogs = NSLocalizedString("_report_logs")
    public static let reportLogsDescription = NSLocalizedString("_report_logs_description")
    public static let reportReport = NSLocalizedString("_report_report")
    public static let reportPlaceholderEmail = NSLocalizedString("_report_placeholder_email")
    public static let reportPlaceholderMessage = NSLocalizedString("_report_placeholder_message")
    public static let reportSend = NSLocalizedString("_report_send")
    public static let reportSuccess = NSLocalizedString("_report_success")
    public static let reportDescription = NSLocalizedString("_report_description")
    public static let reportFieldEmail = NSLocalizedString("_report_field_email")
    public static let reportFieldCountry = NSLocalizedString("_report_field_country")
    public static let reportFieldISP = NSLocalizedString("_report_field_isp")
    public static let reportFieldAccount = NSLocalizedString("_report_field_account")
    public static let reportFieldPlan = NSLocalizedString("_report_field_plan")
    public static let reportFieldVersion = NSLocalizedString("_report_field_version")
    public static let reportFieldFeedback = NSLocalizedString("_report_field_feedback")
    public static let reportAddFile = NSLocalizedString("_report_add_file")
    public static let reportMaxFileSize = NSLocalizedString("_report_max_file_size")
    
}
