
// Objective-C API for talking to the following Go packages
//
//	github.com/ProtonMail/go-srp
//	gitlab.protontech.ch/ProtonVPN/clients-shared/ed25519
//
// File is generated by gomobile bind. Do not edit.
#ifndef __WireguardSRP_FRAMEWORK_H__
#define __WireguardSRP_FRAMEWORK_H__

#include "Srp.objc.h"
#include "Ed25519.objc.h"
#include "Universe.objc.h"

#endif
